"""Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.
"""


def fibonaccis():
    prev = 1
    yield prev
    next = 2
    while True:
        yield next
        tmp = next
        next = prev + next
        prev = tmp

sum = 0
for fibonacci in fibonaccis():
    if fibonacci >= 4000000:
        break
    if not fibonacci % 2:
        sum += fibonacci

print sum
